openapi: 3.0.0

info:
  title: Pets
  version: '1.0-SNAPSHOT'

paths:
  /pets/{petId}:
    get:
      tags:
        - Pet
      summary: Find pet by ID
      description: Returns a single pet
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

components:

  schemas:

    Pet:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        owner:
          $ref: 'users.yaml#/components/schemas/User'