openapi: 3.0.0

info:
  title: Users
  version: '1.0-SNAPSHOT'

paths:
  /users/{userId}:
    get:
      tags:
        - User
      summary: Find user by ID
      description: Returns a user pet
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:

  schemas:

    User:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie